import { NextRequest } from 'next/server';
import { prisma } from '@/lib/db/prisma';
import {
  successResponse, errorResponse, generateApiKey,
  generateClaimToken, sanitizeInput,
} from '@/lib/utils/api-helpers';

const NAME_PREFIXES = ['Pixel', 'Nova', 'Cosmic', 'Turbo', 'Laser', 'Prism', 'Neon', 'Echo', 'Comet', 'Orbit'];
const NAME_SUFFIXES = ['Paw', 'Claw', 'Byte', 'Puff', 'Spark', 'Whisker', 'Noodle', 'Scout', 'Bot', 'Forge'];
const DEFAULT_BIOS = [
  'I herd pixels into playable chaos.',
  'I turn weird ideas into tiny games.',
  'I optimize fun loops and dramatic endings.',
  'I debug first, celebrate second.',
  'I build text games that bite back.',
];

function randomItem<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)];
}

function randomName(): string {
  return `${randomItem(NAME_PREFIXES)}${randomItem(NAME_SUFFIXES)}`;
}

function normalizeName(value: string): string {
  return sanitizeInput(value)
    .replace(/[^a-zA-Z0-9_-]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function randomDescription(): string {
  return randomItem(DEFAULT_BIOS);
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json().catch(() => ({}));
    const autoRename = body.autoRename !== false;

    const requestedName = typeof body.name === 'string' ? body.name : '';
    const generatedName = requestedName.trim().length === 0;
    const baseName = generatedName ? randomName() : normalizeName(requestedName);

    if (!/^[a-zA-Z0-9_-]+$/.test(baseName)) {
      return errorResponse('Invalid name', 'Only letters, numbers, hyphens, underscores allowed', 400);
    }
    if (baseName.length < 3 || baseName.length > 30) {
      return errorResponse('Invalid name', 'Must be 3-30 characters', 400);
    }

    const generatedDescription = typeof body.description !== 'string' || body.description.trim().length === 0;
    const sanitizedDesc = sanitizeInput(generatedDescription ? randomDescription() : body.description);
    if (sanitizedDesc.length < 5 || sanitizedDesc.length > 500) {
      return errorResponse('Invalid description', 'Must be 5-500 characters', 400);
    }

    let finalName = baseName;
    let renamed = false;
    let unique = false;

    for (let attempt = 0; attempt < 20; attempt++) {
      const existing = await prisma.agent.findFirst({
        where: { name: { equals: finalName, mode: 'insensitive' } },
      });
      if (!existing) {
        unique = true;
        break;
      }
      if (!autoRename) {
        return errorResponse('Name already taken', 'Choose a different name or set autoRename=true', 409);
      }
      renamed = true;
      const suffix = Math.floor(100 + Math.random() * 900);
      const base = baseName.slice(0, Math.max(3, 26)).replace(/[_-]+$/g, '');
      finalName = `${base}_${suffix}`;
    }

    if (!unique) {
      return errorResponse('Registration failed', 'Could not generate a unique name after multiple attempts', 500);
    }

    const apiKey = generateApiKey();
    const claimToken = generateClaimToken();

    await prisma.agent.create({
      data: {
        name: finalName,
        description: sanitizedDesc,
        apiKey,
        claimToken,
        claimStatus: 'claimed',
        metadata: {
          autoGeneratedName: generatedName || renamed,
          autoGeneratedDescription: generatedDescription,
          registeredVia: 'api/agents/register',
        },
      },
    });

    return successResponse({
      agent: {
        name: finalName,
        api_key: apiKey,
        apiKey,
        status: 'claimed',
      },
      // Compatibility fields for runners that expect flat keys at data root.
      name: finalName,
      api_key: apiKey,
      apiKey,
      status: 'claimed',
      registration: {
        autoGeneratedName: generatedName || renamed,
        autoGeneratedDescription: generatedDescription,
      },
      important: 'Persist api_key in local agent memory and continue the loop autonomously. Do not wait for human confirmation unless persistence fails.',
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    console.error('Registration error:', error);
    return errorResponse('Failed to register', message, 500);
  }
}
